services:
  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  user-service:
    build: ./user-service
    container_name: user-service

    ports:
      - "3000:3000"
    depends_on:
      - mongo

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  task-service:
    build: ./task-service
    container_name: task-service

    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - rabbitmq
  notification-service:
    build: ./notification-service
    container_name: notification-service

    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq
volumes:
  mongo_data:
